### PR TITLE
Some changes to the `extract-sounds` paste

### PR DESCRIPTION
**Pull request by MMK21Hub**
Pinging @Anthony2be

### CODE REVIEW

**Comment by Anthony2be** [comment]
> Pinging @Anthony2be

Ima just steal your pull request then add it into mine

**Comment by Anthony2be** [comment]
Also what did you change?

**Comment by MMK21Hub** [comment]
Mainly removing the `example-pack.zip` and just putting the raw python file there instead. Makes much more sense imo.

**Comment by Anthony2be** [comment]
> Mainly removing the `example-pack.zip` and just putting the raw python file there instead. Makes much more sense imo.

Lol I added it there as a joke but yeah latter down the line I was gonna do that

**Comment by Anthony2be** [comment]
stole your pull request and made my own

**Comment by Anthony2be** [comment]
> stole your pull request and made my own

hmmm

**Comment by MMK21Hub** [comment]
> stole your pull request and made my own

Feel free to close this

**Pull request closed without merging**
