### PR TITLE
Update raw-paste.txt

### PR DESCRIPTION
**Pull request by Anthony2be**

### CODE REVIEW

**Review by MMK21Hub — CHANGES_REQUESTED** [review]
From what I see, all you've done is removed the Title Formatting, which is against the Contributing Guidelines.

**Comment by Anthony2be** [comment]
no?

**Comment by Anthony2be** [comment]
oh wrong branch :/

**Comment by Anthony2be** [comment]
no this one has all of the reqirements

**Comment by Anthony2be** [comment]
> From what I see, all you've done is removed the Title Formatting, which is against the Contributing Guidelines.

i ADDED the title formatting

**Comment by Anthony2be** [comment]
> ~From what I see, all you've done is removed the Title Formatting.~
> _Oops_

so is it gonna be accepted?

**Review by MMK21Hub — COMMENTED** [review]
Not sure why `example-pack.zip` is needed? a) It's not an example pack so it should be renamed b) At this point just add the raw python file?

Apart from the above and my nitpick, everything looks good.

**Pull request merged**
